spring:
  application:
    name: book-stock
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    compatibility-verifier:
      enabled: false
    sentinel:                      # 👈 新增 Sentinel 配置
      transport:
        dashboard: localhost:8858
        port: 8719
      eager: true
      datasource:
        flow-rules: # 流控规则数据源（名字可自定义）
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: book-stock-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        degrade-rules: # 熔断规则数据源
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: book-stock-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081