spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      server:
        webflux:
          routes:
            - id: order-service-route
              uri: lb://order-service
              predicates:
                - Path=/order-service/**
              filters:
                - StripPrefix=1
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
      eager: true
      datasource:
        gw-flow-rules:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: gateway-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-flow
server:
  port: 8083